name: Get Content from News API

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  schedule:
    - cron: 0 */12 * * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "fetch"
  fetch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Calling News API...
        run: |
          cd news-api-org
          ../fetch-headlines.py \
          "http://newsapi.org/v2/top-headlines?apiKey=${{secrets.NEWS_API_KEY}}" \
          headlines.json \
          us,gb,hk,tw,cn,jp,kr,th,gr,fr,tr,pl,ru,ch,il,eg
          
          npm install
          npm run-script build
          cat countries.json

          git add .
          git config --global user.name $GITHUB_ACTOR
          git diff --quiet && git diff --staged --quiet || git commit -am 'Update news headlines' 
          git push

