name: Get Content

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  schedule:
    - cron: 0 * * * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Calling News API...
        run: |
          git pull
          OUTPUT_FILE="news-api-org/headlines.json"
          curl -X GET \
            --silent \
            -H 'content-type: application/json' \
            -H "x-api-key: ${{secrets.NEWS_API_KEY}}" \
            'http://newsapi.org/v2/top-headlines?country=us&category=business' | json_pp > $OUTPUT_FILE
          git config --global user.name $GITHUB_ACTOR
          git diff --quiet && git diff --staged --quiet || git commit -am 'Update news headlines' 
          git push

      - name: Get latest COVID-19 statistics
        run: |
          git config --global user.name $GITHUB_ACTOR          
          
          cd covid-19

          npm install
          npm start
          
          git add us-states.csv us-states.json
          git diff --quiet && git diff --staged --quiet || git commit -am 'Update Covid news'
          git push
          
      - name: Get USD exchange rates
        run: |
          OUTPUT_FILE=forex-rates.json
          mkdir -p exchangeratesapi && cd exchangeratesapi

          curl -X GET \
            --silent \
            -H 'content-type: application/json' \
            'https://api.exchangeratesapi.io/latest?base=USD' | json_pp > $OUTPUT_FILE

          git config --global user.name $GITHUB_ACTOR
          git diff --quiet && git diff --staged --quiet || git commit -am 'Update USD exchange rates'
          git push

      - name: Get Top Stories
        run: |
          OUTPUT_FILE=movies.json
          mkdir -p nyt && cd nyt
          
          curl -X GET \
            --silent \
            -H 'content-type: application/json' \
            https://api.nytimes.com/svc/topstories/v2/movies.json?api-key=${{secrets.NYT_API_KEY}} | json_pp > $OUTPUT_FILE
            
          git config --global user.name $GITHUB_ACTOR
          git diff --quiet && git diff --staged --quiet || git commit -am 'Update Top Stories on Movies'
          git push
