name: Get Content

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  schedule:
    - cron: 0 */12 * * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      - name: Get USD exchange rates
        run: |
          OUTPUT_FILE=usd.json
          git pull
          mkdir -p finnhub && cd finnhub
         
          npm install
          node fetch-usd.js ${{secrets.FINNHUB_API_KEY}}
          
          git config --global user.name $GITHUB_ACTOR
          git add usd.json
          git diff --quiet && git diff --staged --quiet || git commit -am 'Update USD exchange rates'
          git push
      
