name: Get News Headlines

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: 0 * * * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Calling News API...
        run: |
          OUTPUT_FILE="news-api-org/headlines.json"
          curl -X GET \
            --silent \
            -H 'content-type: application/json' \
            -H "x-api-key: ${{secrets.NEWS_API_KEY}}" \
            'http://newsapi.org/v2/top-headlines?country=us&category=business' | json_pp > $OUTPUT_FILE
          git config --global user.name $GITHUB_ACTOR
          git add $OUTPUT_FILE
          git commit -m "Update news headlines"
          git push

      - name: Get Top Stories from FinnHub
        run: |
          git config --global user.name $GITHUB_ACTOR
          URL='https://finnhub.io/api/v1/news?category=general'
          
          mkdir -p finnhub && cd finnhub
          
          curl -X GET \
            --silent \
            -H 'content-type: application/json' \
            -H "X-Finnhub-Token : ${{secrets.FINNHUB_API_KEY}}" \
            $URL | json_pp > marketnews.json
            
          git add . && git commit -m "Update market news" && git push

      - name: Get latest COVID-19 statistics
        run: |
          git config --global user.name $GITHUB_ACTOR
          URL='https://finnhub.io/api/v1/covid19/us'
          
          mkdir -p finnhub && cd finnhub

          curl -X GET \
            --silent \
            -H 'content-type: application/json' \
            -H "X-Finnhub-Token : ${{secrets.FINNHUB_API_KEY}}" \
            $URL | json_pp > covid.json
          git add . && git commit -m "Update Covid news" && git push
